name: UPM Package

on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@careboo'
    - run: npm publish --access public Packages/com.careboo.serially
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
