name: Publish UPM Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@careboo'

    - name: Publish to GitHub Package Repository
      run: npm publish --access public Packages/com.carebo.serially
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
