name: Create Release

on:
  push:
    branches:
      - master
      - preview
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.x'
      - '[0-9]+.x.x'

jobs:
  release:
    name: Release New Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Semantic release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2.1.3
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@careboo'
      
      - name: Publish to GitHub Package Repository
        if: steps.semantic.outputs.new_release_published == 'true'
        run: npm publish --access public Packages/com.carebo.serially
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
