name: Unity Tests

on:
  push:
    branches:
      - master
  pull_request:

env:
  UNITY_LICENSE_2019: ${{ secrets.UNITY_LICENSE_2019 }}
  UNITY_LICENSE_2020: ${{ secrets.UNITY_LICENSE_2020 }}

jobs:
  testAllModes:
    name: Test on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - .
        unityVersion:
          - 2019.4.2f1
          - 2020.2.1f1

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set Unity License
        env:
          UNITY_VERSION: ${{ matrix.unityVersion }}
        run: |
          eval "license=\$UNITY_LICENSE_${UNITY_VERSION:0:4}"
          echo "UNITY_LICENSE=$license"

      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.unityVersion }}
          restore-keys: |
            Library-
      - uses: game-ci/unity-test-runner@v2.0-alpha-1
        id: tests
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          artifactsPath: TestResults
          customParameters: -enableCodeCoverage -coverageOptions generateAdditionalMetrics;enableCyclomaticComplexity;assemblyFilters:+CareBoo*,-CareBoo*.Tests,-CareBoo*.Samples.*
      - name: Upload Test Results Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Test results
          path: ${{ steps.tests.outputs.artifactsPath }}
      - name: Upload Code Coverage Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Code Coverage
          path: ./CodeCoverage
      - name: Upload PlayMode Test Coverage Report
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          file: ./CodeCoverage/workspace-opencov/PlayMode/TestCoverageResults_0000.xml
      - name: Upload EditMode Test Coverage Report
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          file: ./CodeCoverage/workspace-opencov/EditMode/TestCoverageResults_0000.xml
